execute pathogen#infect()
filetype plugin indent on
syntax on
set number
set showmatch
set mouse=a
set cursorline
set hlsearch
set ignorecase
set wildmenu
set wildmode=list:longest,full
set foldenable
set smarttab
set nobackup
set shiftwidth=4
set backspace=2
nmap <Space> i
inoremap <C-p> <Esc> :r ! xsel -p<CR> 
nnoremap <C-p> :r ! xsel -p<CR>
let Tlist_Compact_Format = 1
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Close_On_Select = 1
nnoremap <silent> <F8> :TlistToggle<CR>
nnoremap <silent> <F7> :NERDTreeToggle<CR>
